export * from './Login'
export * from './Register'
export * from './app'
export * from './ForgotPassword'
export * from './TermsOfUse'
export * from './PrivacyPolicy'
export * from './KYC'
export * from './VerifyAccount'